from enum import Enum

class TransactionType(Enum):
    STOCK_ADDED="STOCK_ADDED"
    STOCK_REMOVED="STOCK_REMOVED"
    STOCK_RELEASED="STOCK_RELEASED"
    STOCK_RESERVED="STOCK_RESERVED"
    STOCK_TRANSFERED="STOCK_TRANSFERED"
